### ISSUE TITLE
How to build audiobuffersplit?

### ISSUE THREAD

**Issue by cwaldren** [OSSystems/meta-gstreamer1.0#25] opened 2019-02-19 01:52 UTC
I am trying to include the `audiobuffersplit` plugin from `gstreamer1.0-plugins-bad` in my image. 

I looked through previous issues, thinking I'd be able to figure this out on my own, but to no avail.

I added:

 `PACKAGECONFIG_append_pn-gstreamer1.0-plugins-bad = " audiobuffersplit"` 

and 

`IMAGE_INSTALL_append = " gstreamer1.0-plugins-bad-audiobuffersplit'` -> (Couldn't find anything to satisfy 'gstreamer1.0-plugins-bad-audiobuffersplit')

to `local.conf`, but I think I am fundamentally missing something - either a detail or a theoretical misunderstanding. 

Any help would be greatly appreciated.

**Comment by philn** [comment] 2019-04-23 19:10
There's currently no packageconfig option for `audiobuffersplit`. See https://github.com/OSSystems/meta-gstreamer1.0/blob/master/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.14.4.bb#L38 (unless I missed it, feel free to send a PR :))

**Comment by dv1** [comment] 2019-05-26 07:54
I cannot reproduce the problem. audiobuffersplit gets automatically built both with 1.14.4 and 1.16.0 recipes. With both versions, I can find a `gstreamer1.0-plugins-bad-audiobuffersplit_*` package after building -bad. Try again with newer versions, and check in the deploy directory that a package with "audiobuffersplit" in its filename is present.

Closing for now, reopen if the problem persists.

**Closed as completed by dv1** 2019-05-26 07:54 UTC
